### ISSUE TITLE
Pydio Sync agent not running on Mac'OS Yosemite

### ISSUE THREAD

**Issue by hgpestana** [pydio/pydio-sync#101]
Hi all,

Just downloaded and installed the stable pydio-sync client from site and ran into a couple of issues that are preventing the client to start. First, the client would not start after installation or on double click. On further investigation, I saw that the launchctl could not run the client due to wrong permissions (ownership set by default to administrator:staff without +x permissions in the agent). After correcting, the sync agent still won't start due to the following error in the JavaApplicationStub:

[JavaAppLauncher Error] CallStaticVoidMethod() threw an exception
Exception in thread "main" java.lang.NoClassDefFoundError: org/quartz/SchedulerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at apple.launcher.LaunchRunner.loadMainMethod(LaunchRunner.java:56)
	at apple.launcher.LaunchRunner.run(LaunchRunner.java:112)
	at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:51)
	at apple.launcher.JavaApplicationLauncher.launch(JavaApplicationLauncher.java:52)
Caused by: java.lang.ClassNotFoundException: org.quartz.SchedulerException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 6 more
Tried to update the JRE and Java SDK to latest but still to no avail. Can anyone help in this situation?

Thanks,
Hélder

**Comment by hgpestana** [comment]
My bad,

Don't know why, but I kept running into the old client through the website. Found the new one. 

Thanks,
