### ISSUE TITLE
Not working with config file

### ISSUE THREAD

**Issue by lludol** [pydio/pydio-sync#121]
Hello,

I have installed Pydio on my Debian wheezy server, it's working but the desktop client is not working on laptop (I have Debian LMDE).

I don't need the UI, so I have installed pydio-sync with pip.

If I launch the client like that, it's working:
```
python -m pydio.main --server=https://mycloud --directory=/home/lludol/Pydio --workspace=my-files --user=lludol --password="mypassword"
```

But I launch the client with a config file, it's not working:
My config file: 
```json
[
    {
        "__type__"  : "JobConfig",
        "server"    : "https://mycloud",
        "workspace" : "my-files",
        "directory" : "/home/lludol/Pydio",
        "user"      : "lludol",
        "password"  : "mypassword",
        "direction" : "bi",
        "active"    : true
    }
]
```

And the command line:
```
python -m pydio.main --file=/home/lludol/Documents/pydio-sync-config.json
```

The error:
```
20:46:41 INFO    139733412087552 MainThread Loading config from /home/lludol/Documents/pydio-sync-config.json
20:46:42 INFO    139733412087552 MainThread -----------------------------------------------
20:46:42 INFO    139733412087552 MainThread Starting agent locally on http://localhost:5556/
20:46:42 INFO    139733412087552 MainThread ------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/pydio/main.py", line 318, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pydio/main.py", line 251, in main
    scheduler.start_all()
  File "/usr/local/lib/python2.7/dist-packages/pydio/job/scheduler.py", line 44, in start_all
    job_config = self.job_configs[job_id]
TypeError: object cannot be interpreted as an index
```

**What I am doing wrong?**

I have cloned this repo because the executable that we can get in the pydio website is not working:
```
./pydio-agent: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
```

**Comment by sagaru** [comment]
Hello,

Its not working as the format of the configs.json file is incorrect.

You've just entered the job config value while missing its key(see snippet below).

```
{
  "my-files-1": {
        "__type__"  : "JobConfig",
        "server"    : "https://mycloud",
        "workspace" : "my-files",
        "directory" : "/home/lludol/Pydio",
        "user"      : "lludol",
        "password"  : "mypassword",
        "direction" : "bi",
        "active"    : true
    }
}
```
I'm closing this issue, If you have questions, consider posting it on our dedicated forum meant for these, once it is qualified as a bug, you can post here.
https://pydio.com/en/community
