### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by DesMas** [pydio/pydio-sync#131]
I've installed the version 1.2.0 on my Mint 17 64bit OS and tried to synch some folders with non-ascii characters in the names.
This failed with the log message: 
`2016-03-25 11:42:32 ERROR   140638299334400 Thread-1 logging : 1575 | error | 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.continous_merger", line 383, in run
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.local_watcher", line 132, in check_from_snapshot
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 226, in __init__
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 211, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/posixpath", line 71, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
2016-03-25 11:42:32 ERROR   140638299334400 Thread-1 logging : 1575 | error | 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
2016-03-25 11:42:32 INFO    140638290941696 Thread-2 logging : 1600 | info | Starting permanent monitor`

Therefore i checked the locale settings and also set the following code in ~/.profile ans also ~/.bashrc with no success:
`
export LC_ALL=de_DE.UTF-8
export LANG=de_DE.UTF-8
export LANGUAGE=de_DE.UTF-8
`

**Comment by 7omate** [comment]
Did you have a sync previously?

**Comment by DesMas** [comment]
well, only with a test file due this was a fresh install to test this tool

**Comment by 7omate** [comment]
Could you try with a new sync ?
How are you runnning it on linux? (did you activate some debug parameters?)

**Comment by DesMas** [comment]
I've downloaded the client as binary package from the page "https://pydio.com/en/products/downloads/pydiosync-desktop-app" and copied the two directories to "/opt".
Then I added the client binary file to the startup programs, started and configured it.

**Comment by DesMas** [comment]
ok, I see my fault.. the binary is not working the same way as the source....
I just cloned the project and started the client with "python -m pydio.main" which than uses the already existing config in my user profile.
This seems to be working.
This leads to a new Question.. how to create a new set of binarys...

**Comment by 7omate** [comment]
I'm relieved it's working :)
We use pyinstaller to build binaries. It's a bit of a mess... Ideally this would work:
pip install pyinstaller && pyinstaller main.py && pyinstaller main.spec
