### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)

### ISSUE THREAD

**Issue by fnkr** [pydio/pydio-sync#132]
Initial sync fails if there are non-ASCII filenames to sync, e.g.

```
Español.qm
漢語.qm
Português (Brasil).qm
Français.qm
русский язык.qm
한국어.qm
汉语.qm
日本語.qm
Ελληνικά.qm
Français.lng
Español.lng
Türkçe.lng
```

```
DEBUG:root:sys.path: /tmp/_MEIehK5WW
	/mnt/data/Downloads/pydio-agent
DEBUG:root:PYTHONPATH: /tmp/_MEIehK5WW
DEBUG:root:sys.getdefaultencoding(): ascii
DEBUG:root:sys.getfilesystemencoding(): None
DEBUG:root:sys.platform: linux2
DEBUG:root:pydio_module: /mnt/data/Downloads/pydio-ui
INFO:root:Linux CONFIG DIR EXPANDED: /home/fnkr/.local/share
INFO:root:Linux DEFAULT_DATA_PATH: /home/fnkr/.local/share/Pydio
02:49:14 INFO    140273200830208 MainThread Product Version Number 1.2.0 and Version Date March 15 2016
02:49:14 INFO    140273200830208 MainThread -----------------------------------------------
02:49:14 INFO    140273200830208 MainThread Starting agent locally on http://localhost:5556/
02:49:14 INFO    140273200830208 MainThread ------------------------------------------------
02:49:15 INFO    140273200830208 MainThread Structure and Integrity of SQLite file /home/fnkr/.local/share/Pydio/pydio.fnkr.net-my-files/pydio.sqlite is intact 
02:49:15 INFO    140272973068032 Thread-1 Scanning for changes since last application launch
02:49:15 ERROR   140272973068032 Thread-1 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.continous_merger", line 383, in run
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.local_watcher", line 132, in check_from_snapshot
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 226, in __init__
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 223, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 223, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 223, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 223, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 223, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 211, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/posixpath", line 71, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
02:49:15 ERROR   140272973068032 Thread-1 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
02:49:15 INFO    140272893687552 Thread-2 Starting permanent monitor
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/threading", line 551, in __bootstrap_inner
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.observers.api", line 182, in run
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.observers.polling", line 78, in queue_events
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.observers.polling", line 74, in <lambda>
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 226, in __init__
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 223, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 223, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 223, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 223, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 223, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/watchdog.utils.dirsnapshot", line 211, in walk
  File "/home/parallels/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/posixpath", line 71, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```

**Comment by 7omate** [comment]
Hi, could you tell me a bit more about your set up? What distribution are you using?
**DEBUG:root:sys.getfilesystemencoding(): None** I usually get utf-8 there.

**Comment by fnkr** [comment]
I'm using Fedora 23 with english language and german measurement units. Strange, if I start Python manually, it returns `UTF-8`.

```
$ python
Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getfilesystemencoding()
'UTF-8'
>>> 
[  #2 ] [ fnkr@idle ] [ ~ ] [ master - ] 
$ python3
Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getfilesystemencoding()
'utf-8'
>>> 
```

**Comment by 7omate** [comment]
Uhm... Weird, I'll try to understand what's going on here, in the mean time you might want to try running from the source.

**Comment by 7omate** [comment]
It's patched, the solution isn't great but should work for most...
