### ISSUE TITLE
MacOSX: SSL: SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by dnauck** [pydio/pydio-sync#151]
Hello,

the pydio sync client 1.2.8 fails on mac osx 10.11.6 with:

	2016-11-07 11:59:13 INFO    123145328156672 Thread-3 logging : 1627 | info | Loading remote changes with sequence 124 for job id workspace.example.com-project-123456
	2016-11-07 11:59:13 ERROR   123145328156672 Thread-3 logging : 1601 | error | [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
	Traceback (most recent call last):
	  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.continous_merger", line 464, in run
	  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.continous_merger", line 786, in load_remote_changes_in_store
	  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdkremote.remote", line 418, in changes_stream
	  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdkremote.remote", line 330, in perform_request
	  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdkremote.remote", line 225, in perform_basic
	  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/requests.api", line 65, in get
	  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/requests.api", line 49, in request
	  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/requests.sessions", line 461, in request
	  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/requests.sessions", line 573, in send
	  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/requests.adapters", line 431, in send
	SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

While working on Windows.

The nginx settings:

    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers EECDH+AESGCM:EDH+AESGCM:EECDH:EDH:!MD5:!RC4:!LOW:!MEDIUM:!CAMELLIA:!ECDSA:!DES:!DSS:!3DES:!NULL;

**Comment by 7omate** [comment]
Can you give your server URL and maybe a test account?

I don't have a spare signed certificate to test those settings

**Comment by 7omate** [comment]
As far as I remember we ship a more recent openssl version for Mac to support TLS 1.2, from some random internet posts it seems like autorizing MD5 could solve it... Can you try that?

If you don't have time to look deeper and no one else is interested I'll close this.
