### ISSUE TITLE
You must not use 8-bit bytestrings

### ISSUE THREAD

**Issue by MrMEEE** [pydio/pydio-sync#165]
Hi

I got the following error, both on my Windows and Linux clients.. 

After settings the base language on the pydio server to da_DK.UTF-8, it disappeared on my Windows clients...

But the Linux Clients keeps failing.. seems to have something to do with my danish letter: øæå...

What to do..???

/Martin

13:38:48 ERROR   139763966973696 Thread-2 Unexpected Error: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
Traceback (most recent call last):
  File "/home/mj/Programmer/Pydio-new/pydio-agent/pydio-sync/src/pydio/job/continous_merger.py", line 566, in run
    store_conflicts = self.current_store.clean_and_detect_conflicts(self.db_handler)
  File "/home/mj/Programmer/Pydio-new/pydio-agent/pydio-sync/src/pydio/job/change_stores.py", line 536, in clean_and_detect_conflicts
    status_handler.update_node_status(path, 'CONFLICT', self.sqlite_row_to_dict(row, load_node=True))
  File "/home/mj/Programmer/Pydio-new/pydio-agent/pydio-sync/src/pydio/job/localdb.py", line 317, in update_node_status
    conn.execute("UPDATE ajxp_node_status SET status=?, detail=? WHERE node_id=?", (status, detail, node_id))
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by bambooLoutre** [comment]
same here on windows (PydioSync v1.2.9)
![image](https://user-images.githubusercontent.com/7150769/42946252-b750b49a-8b6a-11e8-8b8c-3c7d274657a2.png)

**Comment by simon-hartmann** [comment]
Same here for one user.

**Comment by cdujeu** [comment]
we're on it

**Comment by jabarkarim** [comment]
Hi there,

Here is where you can get the Pydio Sync client latest improvements for Windows and OSX:
https://download.pydio.com/pub/pydio-sync/develop/packages/

Please try it and let us know if it helps.

Regards

**Comment by kingfisher77** [comment]
It seems to work on macOS! 👍

**Comment by bambooLoutre** [comment]
Seems to work on Windows too :+1:
