### ISSUE TITLE
ImportError: No module named job.EventLogger

### ISSUE THREAD

**Issue by jkirk** [pydio/pydio-sync#171]
Please help me with this one.

I am running Debian/stretch and did the following:
```
% sudo apt install python-virtualenv python-dev libffi-dev
% virtualenv -p $(which python2) venv
% venv/bin/pip install git+https://github.com/pydio/pydio-sync.git
% source venv/bin/activate
% python -m pydio.main
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jkirk/software/virtualenv/venv/lib/python2.7/site-packages/pydio/main.py", line 46, in <module>
    from ui.web_api import PydioApi
  File "/home/jkirk/software/virtualenv/venv/local/lib/python2.7/site-packages/pydio/ui/web_api.py", line 60, in <module>
    from job.EventLogger import EventLogger
ImportError: No module named job.EventLogger
```
Did I do something wrong or is this a (known) bug?

**Comment by jkirk** [comment]
Seems to come from this commit: https://github.com/pydio/pydio-sync/commit/31e42a553bdc4863c6e2305f6a1afab1f98a2eb2#r30279877

**Comment by jkirk** [comment]
This is duplicate of https://github.com/pydio/pydio-sync/issues/175. Closing.
