### ISSUE TITLE
can't run pydio.main 

### ISSUE THREAD

**Issue by hemna** [pydio/pydio-sync#175]
just cloned the latest from the git repo and created a python2 virtualenv and pydio.main won't run.

└─[$] <git:(master*)> python -m pydio.main
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/waboring/pydio/pydio-sync/.venv/lib/python2.7/site-packages/pydio/main.py", line 41, in <module>
    from job.job_config import JobConfig, JobsLoader
  File "/home/waboring/pydio/pydio-sync/.venv/lib/python2.7/site-packages/pydio/job/__init__.py", line 29, in <module>
    from sdkremote.remote import Waiter
ImportError: No module named sdkremote.remote

**Comment by DjZU** [comment]
You need to `git submodule update --init`
