### ISSUE TITLE
Http-Basic authentication failed, wrong credentials? (after upgrade to Debian/buster)

### ISSUE THREAD

**Issue by jkirk** [pydio/pydio-sync#182]
After the upgrade from Debian/stretch to Debian/buster, `pydio-agent` fails to connect to an already configured workspace with the following error:

```
10:47:11 INFO    140186165586816 MainThread Product Version Number 1.2.7 and Version Date July 27 2016
10:47:11 INFO    140186165586816 MainThread -----------------------------------------------
10:47:11 INFO    140186165586816 MainThread Starting agent locally on http://localhost:5556/
10:47:11 INFO    140186165586816 MainThread ------------------------------------------------
10:47:11 INFO    140186165586816 MainThread Structure and Integrity of SQLite file /home/steffi/.local/share/Pydio/archiv.example.com-steffi/changes.sqlite is intact■
10:47:11 INFO    140186165586816 MainThread Structure and Integrity of SQLite file /home/steffi/.local/share/Pydio/archiv.example.com-steffi/pydio.sqlite is intact■
10:47:11 INFO    140186165586816 MainThread Structure and Integrity of SQLite file /home/steffi/.local/share/Pydio/archiv.example.com-steffi/history.sqlite is intact■
10:47:11 INFO    140186165586816 MainThread Structure and Integrity of SQLite file /home/steffi/.local/share/Pydio/archiv.example.com-my-files/changes.sqlite is intact■
10:47:11 INFO    140186043488000 Thread-1 Scanning for changes since last application launch
10:47:11 INFO    140186165586816 MainThread Structure and Integrity of SQLite file /home/steffi/.local/share/Pydio/archiv.example.com-my-files/pydio.sqlite is intact■
10:47:11 INFO    140186165586816 MainThread Structure and Integrity of SQLite file /home/steffi/.local/share/Pydio/archiv.example.com-my-files/history.sqlite is intact■
10:47:11 INFO    140186165586816 MainThread Structure and Integrity of SQLite file /home/steffi/.local/share/Pydio/archiv.example.com-lw/changes.sqlite is intact■
10:47:11 INFO    140186165586816 MainThread Structure and Integrity of SQLite file /home/steffi/.local/share/Pydio/archiv.example.com-lw/pydio.sqlite is intact■
10:47:11 INFO    140186165586816 MainThread Structure and Integrity of SQLite file /home/steffi/.local/share/Pydio/archiv.example.com-lw/history.sqlite is intact■
10:47:11 INFO    140186034833152 Thread-3 Scanning for changes since last application launch
10:47:11 INFO    140186026178304 Thread-5 Scanning for changes since last application launch
10:47:12 INFO    140186014902016 Thread-2 Starting permanent monitor
10:47:12 INFO    140186043488000 Thread-1 Loading remote changes with sequence 48266 for job id archiv.example.com-steffi
10:47:12 INFO    140185514260224 Thread-6 Starting permanent monitor
10:47:12 INFO    140186026178304 Thread-5 Loading remote changes with sequence 48266 for job id archiv.example.com-lw
10:47:12 INFO    140185488819968 Thread-4 Starting permanent monitor
10:47:12 INFO    140186034833152 Thread-3 Loading remote changes with sequence 48266 for job id archiv.example.com-my-files
10:47:12 ERROR   140186034833152 Thread-3 Http-Basic authentication failed, wrong credentials?
Traceback (most recent call last):
  File "/home/pydio/tcAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.continous_merger", line 460, in run
  File "/home/pydio/tcAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.continous_merger", line 771, in load_remote_changes_in_store
  File "/home/pydio/tcAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdkremote.remote", line 407, in changes_stream
  File "/home/pydio/tcAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdkremote.remote", line 324, in perform_request
  File "/home/pydio/tcAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdkremote.remote", line 184, in basic_authenticate
PydioSdkBasicAuthException: Http-Basic authentication failed, wrong credentials? 
```

**Comment by jkirk** [comment]
After some research, it seems that `pydio-agent` needs `gir1.2-gnomekeyring-1.0` (= [libgnome-keyring](https://packages.debian.org/source/stretch/libgnome-keyring) which has been removed from Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941821. "The libgnome-keyring library is deprecated and its usage is strongly discouraged": https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892359

Does anyone know where to find the binary build instructions?

As a workaround, I downloaded and installed [gir1.2-gnomekeyring-1.0](https://packages.debian.org/stretch/amd64/gir1.2-gnomekeyring-1.0/download) + [libgnome-keyring0](https://packages.debian.org/stretch/amd64/libgnome-keyring0/download) + [libgnome-keyring-common](https://packages.debian.org/stretch/all/libgnome-keyring-common/download) from Debian/stretch:

`% sudo dpkg -i gir1.2-gnomekeyring-1.0_3.12.0-1+b2_amd64.deb libgnome-keyring0_3.12.0-1+b2_amd64.deb libgnome-keyring-common_3.12.0-1_all.deb`
