### ISSUE TITLE
Pydio Sync : UnicodeDecodeError

### ISSUE THREAD

**Issue by Natopsi** [pydio/pydio-sync#71]
Hello,

I installed the latest alpha version of Pydio sync <b>client</b> v0.9 and the agent web UI don't work:
"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

Looking at the logs, I get this error appearing at each time I try to access the web ui:
"2014-11-23 00:00:10 ERROR   6756  Dummy-1  flask.app:1423 | log_exception | Exception on /res/index.html [GET]
Traceback (most recent call last):
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\flask.app", line 1817, in wsgi_app
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\flask.app", line 1477, in full_dispatch_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\flask_restful", line 258, in error_router
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\flask.app", line 1381, in handle_user_exception
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\flask.app", line 1475, in full_dispatch_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\flask.app", line 1461, in dispatch_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\flask.helpers", line 822, in send_static_file
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\flask.helpers", line 616, in send_from_directory
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\flask.helpers", line 498, in send_file
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\mimetypes", line 297, in guess_type
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\mimetypes", line 358, in init
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\mimetypes", line 258, in read_windows_registry
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\mimetypes", line 249, in enum_types
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 3: ordinal not in range(128)"

I am running on Windows 7 Pro 64bits, and a standard installation of python 3.4.2 64 bits is installed on my computer for development purposes.

Tested several versions of pydio-sync-agent including old versions from this summer and always the same issue.

**Comment by corwinou** [comment]
Hello !
I also have the same issue on XP SP3. I tried the pydio-sync-agent-win-latest.exe from 07-Jan, still not compatible with 32bit :o(
In a couple of days I will have several computers with Windows 7 x86, I'm afraid it will not work either... 
How do we continue ?

**Comment by cdujeu** [comment]
see #77 we'll try to do that asap

**Comment by corwinou** [comment]
merci !
je peux aider si besoin

**Comment by cdujeu** [comment]
@corwinou can you check #77 (and post comment in this other issue if necessary)

**Comment by jogit** [comment]
Hello ! 
I also have the same issue on Windows 8.1 Pro x64
With PydioSync 0.8.10
My username is "Jérôme" and in the logfile (C:\Users\Jérôme\.pydio_data\pydio.log) I get this error : 

2015-02-01 22:54:48 ERROR   3600  Dummy-1  logging:1193 | exception | Internal Error
Traceback (most recent call last):
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask.app", line 1475, in full_dispatch_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask.app", line 1461, in dispatch_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask_restful", line 397, in wrapper
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask.views", line 84, in view
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask_restful", line 487, in dispatch_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\pydio.ui.web_api", line 286, in get
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\pydio.ui.web_api", line 299, in enrich_job
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\pydio.job.job_config", line 92, in build_job_data_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 10: ordinal not in range(128)


If i use another account with no accentuation all is OK.

**Comment by cdujeu** [comment]
Jérôme it's not the same error. I'll open a new issue for your problem.
