### ISSUE TITLE
Reducing changes - got timeout.

### ISSUE THREAD

**Issue by nordeep** [pydio/pydio-sync#75]
pydio-sync-agent-win_x64-20141216-edcb569.exe

2014-12-19 14:59:25 WARNING 13288 Thread-1 logging:1612 | warning | HTTPConnectionPool(host='pxx.x13yz.net.ru', port=80): Read timed out. (read timeout=20)
2014-12-19 14:59:25 ERROR   13288 Thread-1 logging:1596 | error | sql insert error while trying to log event : Error binding parameter 1 - probably unsupported type. 
2014-12-19 14:59:35 INFO    13288 Thread-1 logging:1622 | info | Loading remote changes with sequence 72891
2014-12-19 14:59:36 INFO    13288 Thread-1 logging:1622 | info | Loading local changes with sequence 1238
2014-12-19 14:59:39 INFO    13288 Thread-1 logging:1622 | info | Reducing changes
2014-12-19 15:00:13 ERROR   13288 Thread-1 logging:1596 | error | Unexpected Error: timed out
Traceback (most recent call last):
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\pydio.job.continous_merger", line 397, in run
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\pydio.job.change_stores", line 254, in detect_unnecessary_changes
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\pydio.job.change_stores", line 279, in filter_w_stat
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\pydio.sdk.remote", line 359, in bulk_stat
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\pydio.sdk.remote", line 225, in perform_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\pydio.sdk.remote", line 192, in perform_with_tokens
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\requests.api", line 88, in post
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\requests.api", line 44, in request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\requests.sessions", line 383, in request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\requests.sessions", line 486, in send
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\requests.adapters", line 394, in send
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\requests.models", line 679, in content
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\requests.models", line 616, in generate
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\requests.packages.urllib3.response", line 236, in stream
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\requests.packages.urllib3.response", line 183, in read
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\httplib", line 549, in read
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\httplib", line 591, in _read_chunked
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-sync-agent-win-latest\out01-PYZ.pyz\socket", line 476, in readline
timeout: timed out
2014-12-19 15:00:23 INFO    13288 Thread-1 logging:1622 | info | Loading remote changes with sequence 72891
2014-12-19 15:00:24 INFO    13288 Thread-1 logging:1622 | info | Loading local changes with sequence 1238
2014-12-19 15:00:27 INFO    13288 Thread-1 logging:1622 | info | Reducing changes
2014-12-19 15:00:50 WARNING 13288 Thread-1 logging:1612 | warning | HTTPConnectionPool(host='pxx.x13yz.net.ru', port=80): Read timed out. (read timeout=20)
2014-12-19 15:00:50 ERROR   13288 Thread-1 logging:1596 | error | sql insert error while trying to log event : Error binding parameter 1 - probably unsupported type. 
2014-12-19 15:01:00 INFO    13288 Thread-1 logging:1622 | info | Loading remote changes with sequence 72891
2014-12-19 15:01:01 INFO    13288 Thread-1 logging:1622 | info | Loading local changes with sequence 1238
2014-12-19 15:01:04 INFO    13288 Thread-1 logging:1622 | info | Reducing changes

On the server side a lot of POST requests:
"POST /api/spacca/stat_hash/iTunes/Music/Gorillaz/Laika%20Come%20Home/07%20Starshine%20(Dub%20_9).m4a HTTP/1.0" 200 98308 "-" "python-requests/2.2.1 CPython/2.7.9 Windows/7"
"POST /api/spacca/stat_hash/iTunes/Music/Gorillaz/On%20Melancholy%20Hill/On%20Melancholy%20Hill%20-%20iTunes%20LP%20(v3..itlp/views/songs.html HTTP/1.0" 200 100171 "-" "python-requests/2.2.1 CPython/2.7.9 Windows/7"
"POST /api/spacca/stat_hash/iTunes/Music/Depeche%20Mode/A%20Broken%20Frame/09%20Shouldn't%20Have%20Done%20That.m4a HTTP/1.0" 200 97149 "-" "python-requests/2.2.1 CPython/2.7.9 Windows/7"

I have some big files about 1-3Gb, and my storage speed is about 20-25MB/s

**Comment by cdujeu** [comment]
Seems like the md5 computation may take to much time indeed. Could you provide me a tmp access to your server to do some debugging?

**Comment by cdujeu** [comment]
This should be fixed in last release, we are dynamically reducing the number of members passed to bulk_stat function if timeout is detected.

**Comment by cdujeu** [comment]
@nordeep any news?

**Comment by nordeep** [comment]
The first working day at 2015!
I will try tonight.

**Comment by nordeep** [comment]
No more timeout!
Thank You!

**Comment by cdujeu** [comment]
Yeah!
