### ISSUE TITLE
Create a win 32bits version

### ISSUE THREAD

**Issue by cdujeu** [pydio/pydio-sync#77]
todo

**Comment by cdujeu** [comment]
Build is available using python 32 on windows. To be checked

**Comment by cdujeu** [comment]
@corwinou can you test https://pyd.io/build/pydio-sync//develop/packages/PydioSync-Windows32-Setup.msi ?

**Comment by corwinou** [comment]
Hello,
I failed to make it run...
I removed the previous version from add/remove programs, then installation okay, after startup I can access the login page http/https and set the server details, but nothing happens after clicking on the submit button : I quickly see "connecting" then I'm back to the login page...
pydio.log contains several times:
2015-01-15 14:40:23 ERROR   2332  Dummy-1  logging:1193 | exception | Internal Error
Traceback (most recent call last):
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask.app", line 1475, in full_dispatch_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask.app", line 1461, in dispatch_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask_restful", line 397, in wrapper
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask.views", line 84, in view
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask_restful", line 487, in dispatch_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\pydio.ui.web_api", line 136, in get
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\requests.api", line 55, in get
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\requests.api", line 44, in request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\requests.sessions", line 383, in request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\requests.sessions", line 486, in send
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\requests.adapters", line 330, in send
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\requests.packages.urllib3.connectionpool", line 480, in urlopen
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\requests.packages.urllib3.connectionpool", line 285, in _make_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\httplib", line 1001, in request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\httplib", line 1035, in _send_request
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\httplib", line 997, in endheaders
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\httplib", line 850, in _send_output
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\httplib", line 812, in send
  File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\requests.packages.urllib3.connection", line 108, in connect
AttributeError: 'NoneType' object has no attribute 'wrap_socket'

- the task manager shows 4 or 5 agent.exe processes, is it intended ?
- the stop.bat script does not work and shows: taskkill.exe error : framedyn.dll not found

**Comment by cdujeu** [comment]
argh.
And this is of course not happening when on a 64 bits system?

**Comment by corwinou** [comment]
You mean on XP x64 ? This is not so usual, I can't test it, but I will try PydioSync-Windows32-Setup.msi on win7 x86 & x64 later this week

**Comment by cdujeu** [comment]
No I meant the 64 package on a 64 system (like win7 or 8). 
But actually I can test the 32 package on a 64 system to see if I reproduce the problem.
Just to make sure, your server is using SSL right?

**Comment by corwinou** [comment]
Ok, so PydioSync-Windows-Setup.msi dated jan-15 is running fine on my french OS (win7 x64), I can synchronise files
Yes, I use SSL

**Comment by cdujeu** [comment]
mm, seems like I can connect successfully using the 32 version on an win7 64...
Will test on an XP at home

**Comment by corwinou** [comment]
ohoh, it also works on a fresh xp sp3 (fr) without automatic update (this was not the case on the other pc). the UI does not start automatically (blank screen without any text or logo), need to kill & restart pydio-ui. Then I was able to log in and lauch the rocket

**Comment by cdujeu** [comment]
can you retry with the last win32 build (from today)? I just tried to upgrade the underlying http requests library.

**Comment by corwinou** [comment]
hum, does not work, only got a blanck page on the UI
two pydio-agent processes started but disappeared after one or two seconds, nothing dated today in the logfile ...

**Comment by cdujeu** [comment]
oups it's not getting better ;-)
same on the "fresh xp sp3" ? 
FYI:
> The white screen is another issue in the UI, we'll solve that
> 2 processes for the agent is normal
> If they disappear, well something crashed :-). 
Can you try to close the UI and relaunch it? 
-c

**Comment by corwinou** [comment]
it works fine on the fresh one, except the white screen, needs to restart the UI, right.
on the customer pc, I killed *pydio*, started first the agent but then it crashed !!

**Comment by cdujeu** [comment]
can you try to manually download the pydio-agent.exe from the build folders, and open a command line and run it ?

**Comment by corwinou** [comment]
I grabbed the pydio-agent.exe dated jan 15 from 
pyd.io/build/pydio-sync//develop/agent/win32, but nothing is displayed 
in the cmd window

**Comment by cdujeu** [comment]
can you grab that one https://pyd.io/build/pydio-sync/develop/agent/win32/pydio-agent-win_x32-20150115-4506064.exe ? 
it's built in debug mode noramlly

**Comment by cdujeu** [comment]
no no forget it
it's not the case

**Comment by cdujeu** [comment]
i'll build it with debug flag

**Comment by cdujeu** [comment]
ok can you try that one? https://pyd.io/build/pydio-sync/develop/agent/win32/pydio-agent-win_x32-20150116-07bc3f3.exe

**Comment by corwinou** [comment]
here is the output

   File 
"C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstalle
r\loader\pyi_importers.py", line 270, in load_module
   File 
"C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150116-0
7bc3f3\out00-PYZ.pyz\requests.packages.urllib3.connectionpool", line 31, 
in <mod
ule>
   File 
"C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstalle
r\loader\pyi_importers.py", line 270, in load_module
   File 
"C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150116-0
7bc3f3\out00-PYZ.pyz\requests.packages.urllib3.connection", line 45, in 
<module>

   File 
"C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstalle
r\loader\pyi_importers.py", line 270, in load_module
   File 
"C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150116-0
7bc3f3\out00-PYZ.pyz\requests.packages.urllib3.util", line 5, in <module>
   File 
"C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstalle
r\loader\pyi_importers.py", line 270, in load_module
   File 
"C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150116-0
7bc3f3\out00-PYZ.pyz\requests.packages.urllib3.util.ssl_", line 12, in 
<module>
   File 
"C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstalle
r\loader\pyi_importers.py", line 270, in load_module
   File 
"C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150116-0
7bc3f3\out00-PYZ.pyz\ssl", line 97, in <module>
   File 
"C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstalle
r\loader\pyi_importers.py", line 414, in load_module
ImportError: DLL load failed: La procÚdure spÚcifiÚe est introuvable.

**Comment by cdujeu** [comment]
yup, reproduced in a VM.

**Comment by cdujeu** [comment]
mmm, really sorry, but currently this is a bit low-priority for me....
WinXP is not even supported anymore by MS ....

**Comment by corwinou** [comment]
Bad news... of course I know that, but it's amazing how many customers 
are still using XP... They do not plan to upgrade anything, they just 
use another browser instead of IE...

**Comment by cdujeu** [comment]
I won't abandon don't worry :-)
Just focusing on fixing the last more important issues, then we'll see what the hell happens on XP.

**Comment by cdujeu** [comment]
Can we just close that one and open a new one with the specific errors, OS version, etc?

**Comment by corwinou** [comment]
ok we'll wait a bit...
it's up to you for this case

**Comment by jrohde** [comment]
Looks like (a part off) this bug has come back since version ```pydio-agent-win_x32-20150224-4feda14``` All versions created after this date fail for me on a Windows Vista 32 bits system with the following trace:

```
Traceback (most recent call last):
File "<string>", line 53, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\pydio.monkeypatch", line 21, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\requests", line 58, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\requests.utils", line 26, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\requests.compat", line 7, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\requests.packages", line 3, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\requests.packages.urllib3", line 10, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\requests.packages.urllib3.connectionpool", line 31, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\requests.packages.urllib3.connection", line 45, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\requests.packages.urllib3.util", line 5, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\requests.packages.urllib3.util.ssl_", line 12, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent-win_x32-20150721-ac0e454\out00-PYZ.pyz\ssl", line 97, in <module>
File "C:\BuildAgent\work\a00136d723583ad3\.distve\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 414, in load_module
ImportError: DLL load failed: Kan opgegeven module niet vinden.
```
I guess i better up the machine to 64 bits system (on Win 7 64 bit it rocks so far!). 
If you rather have this in a new bug, give a shout.
