### ISSUE TITLE
Windows Username with accent

### ISSUE THREAD

**Issue by cdujeu** [pydio/pydio-sync#82]
Hello ! 
I also have the same issue on Windows 8.1 Pro x64
With PydioSync 0.8.10
My username is "Jérôme" and in the logfile (C:\Users\Jérôme.pydio_data\pydio.log) I get this error :

2015-02-01 22:54:48 ERROR 3600 Dummy-1 logging:1193 | exception | Internal Error
Traceback (most recent call last):
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask.app", line 1475, in full_dispatch_request
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask.app", line 1461, in dispatch_request
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask_restful", line 397, in wrapper
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask.views", line 84, in view
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\flask_restful", line 487, in dispatch_request
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\pydio.ui.web_api", line 286, in get
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\pydio.ui.web_api", line 299, in enrich_job
File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\pydio.job.job_config", line 92, in build_job_data_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 10: ordinal not in range(128)

If i use another account with no accentuation all is OK.

**Comment by jogit** [comment]
If you need additional testing. Ask me

**Comment by cdujeu** [comment]
@jogit grab the latest, it should now be fixed
https://pyd.io/build/pydio-sync/develop/packages/

**Comment by jogit** [comment]
Great ! It's work !! 
For me, you can close the issue.

Merci
