### ISSUE TITLE
[osx] Sync error 

### ISSUE THREAD

**Issue by erixtekila** [pydio/pydio-sync#99]
I'm unable to sync a local folder to the server.
Only the folder structure is mirrored, but no fie appears in them.

Here is a stack callback following a fresh pydiosync server startup :

````
Traceback (most recent call last):
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.continous_merger", line 492, in processor_callback
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.change_processor", line 85, in process_change
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.change_processor", line 270, in process_remote_mkfile
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdk.remote", line 552, in mkfile
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdk.remote", line 310, in perform_request
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdk.remote", line 245, in perform_with_tokens
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/requests.api", line 65, in get
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/requests.api", line 49, in request
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/requests.sessions", line 461, in request
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/requests.sessions", line 573, in send
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/requests.adapters", line 433, in send
ReadTimeout: HTTPSConnectionPool(host='cloud.mydomain.net', port=443): Read timed out. (read timeout=20)
````

**Comment by sagaru** [comment]
Hi Eric,

It might be due to the server timeout during download, it has been fixed it in the latest patch

Could you check if the behavior persists with the latest dev release, you can download it from https://pyd.io/build/pydio-sync/develop/packages/

**Comment by cdujeu** [comment]
Please Eric, as stated already, we ask you to post in the forum to get proper instructions, and only once a bug is "qualified", post in github. Thanks.

**Comment by erixtekila** [comment]
Sorry @cdujeu, but I've never been asked to follow such a procedure… which i understand nevertheless.
